apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2024-07-01T05:35:53Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
    operators.operatorframework.io/project_layout: unknown
  name: osd-example-operator-bundle.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Example
      name: examples.managed.openshift.io
      version: v1alpha1
  description: Osd Example Operator Bundle description. TODO.
  displayName: Osd Example Operator Bundle
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: example
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: example
          strategy: {}
          template:
            metadata:
              labels:
                name: example
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                      - key: node-role.kubernetes.io/infra
                        operator: Exists
                    weight: 1
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: example
                image: "quay.io/redhat-user-workloads/oeo-cicada-tenant/osd-example-operator/osd-example-operator-main@sha256:6448509642431509c1032b2cc6bb687b1f5a4515cafe2e1318faf37be4bfa7bb"
                imagePullPolicy: Always
                name: example
                resources: {}
              serviceAccountName: example
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/infra
                operator: Exists
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - osd-example-operator-bundle
  links:
  - name: Osd Example Operator Bundle
    url: https://osd-example-operator-bundle.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.1.0
