apiVersion: apps/v1
kind: Deployment
metadata:
  name: osd-example-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: osd-example-operator
  template:
    metadata:
      labels:
        name: osd-example-operator
    spec:
      serviceAccountName: osd-example-operator
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      containers:
        - name: osd-example-operator
          image: quay.io/redhat-user-workloads/oeo-cicada-tenant/osd-example-operator/osd-example-operator-main@sha256:7c1dc71157fe2e8dc7718eb17ee53516400bf4f60c6f2690a71921404a0ac62a
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "osd-example-operator"
